In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
from PIL import Image
import numpy as np
import io

In [0]:


import pandas as pd

In [0]:
training_df = pd.read_csv(io.StringIO(uploaded['train.csv'].decode('utf-8')))

In [0]:
training_df

Id      DGCI
0    41367835 -0.320235
1    56194592 -0.322221
2    75713836 -0.312795
3     1169576 -0.312034
4    88155343 -0.318707
5    23846130 -0.297002
6    86412085 -0.345611
7    29285287 -0.354862
8     2898685 -0.256450
9    73481093 -0.263790
10   88722947 -0.359695
11   43931561 -0.298957
12   91992792 -0.362399
13    1520521 -0.359806
14   98700810 -0.333367
15   94175976 -0.349142
16   52853784 -0.353877
17   93421283 -0.378145
18    9502570 -0.369674
19   46731836 -0.354539
20   68299038 -0.354239
21   46714742 -0.365900
22   81446350 -0.357382
23   55272055 -0.398346
24   53464994 -0.386132
25   55034797 -0.404669
26   37431788 -0.421733
27   78397360 -0.341485
28   30705324 -0.282712
29   57307709 -0.326052
..        ...       ...
762  23141518  0.489607
763  32042945  0.539986
764   2768556  0.507526
765   3851959  0.517953
766  73577492  0.518205
767   5261797  0.543123
768  37970544  0.524805
769  80652213  0.491058
770  59398745  0.519899
771  50923067  0.536154
772  19784693  0.494990
773  16057761 -0.322581
774  96891713 -0.322581
775  83402169 -0.322581
776  86756580 -0.322581
777  83343852 -0.322581
778  30053949 -0.322581
779  24421998 -0.322581
780  79900074  0.528912
781  40746744  0.516334
782  89637105  0.513656
783  81655269  0.519678
784  63375921  0.479163
785  55612980  0.489307
786  40818131  0.470935
787  78291839  0.490104
788  88429844  0.499334
789  28143562  0.515634
790  69056798  0.519892
791  67464389  0.451200

[792 rows x 2 columns]

In [0]:
appended_df = pd.DataFrame()
appended_df['ResultColumn']=[str(x)+'.jpg' for x in training_df['Id']]

In [0]:
appended_df

ResultColumn
0    41367835.jpg
1    56194592.jpg
2    75713836.jpg
3     1169576.jpg
4    88155343.jpg
5    23846130.jpg
6    86412085.jpg
7    29285287.jpg
8     2898685.jpg
9    73481093.jpg
10   88722947.jpg
11   43931561.jpg
12   91992792.jpg
13    1520521.jpg
14   98700810.jpg
15   94175976.jpg
16   52853784.jpg
17   93421283.jpg
18    9502570.jpg
19   46731836.jpg
20   68299038.jpg
21   46714742.jpg
22   81446350.jpg
23   55272055.jpg
24   53464994.jpg
25   55034797.jpg
26   37431788.jpg
27   78397360.jpg
28   30705324.jpg
29   57307709.jpg
..            ...
762  23141518.jpg
763  32042945.jpg
764   2768556.jpg
765   3851959.jpg
766  73577492.jpg
767   5261797.jpg
768  37970544.jpg
769  80652213.jpg
770  59398745.jpg
771  50923067.jpg
772  19784693.jpg
773  16057761.jpg
774  96891713.jpg
775  83402169.jpg
776  86756580.jpg
777  83343852.jpg
778  30053949.jpg
779  24421998.jpg
780  79900074.jpg
781  40746744.jpg
782  89637105.jpg
783  81655269.jpg
784  63375921.jpg
785  55612980.jpg
786  40818131.jpg
787  78291839.jpg
788  88429844.jpg
789  28143562.jpg
790  69056798.jpg
791  67464389.jpg

[792 rows x 1 columns]

In [0]:
filelist= appended_df["ResultColumn"].tolist()

In [0]:
filelist

['41367835.jpg',
 '56194592.jpg',
 '75713836.jpg',
 '1169576.jpg',
 '88155343.jpg',
 '23846130.jpg',
 '86412085.jpg',
 '29285287.jpg',
 '2898685.jpg',
 '73481093.jpg',
 '88722947.jpg',
 '43931561.jpg',
 '91992792.jpg',
 '1520521.jpg',
 '98700810.jpg',
 '94175976.jpg',
 '52853784.jpg',
 '93421283.jpg',
 '9502570.jpg',
 '46731836.jpg',
 '68299038.jpg',
 '46714742.jpg',
 '81446350.jpg',
 '55272055.jpg',
 '53464994.jpg',
 '55034797.jpg',
 '37431788.jpg',
 '78397360.jpg',
 '30705324.jpg',
 '57307709.jpg',
 '17007478.jpg',
 '9762044.jpg',
 '40097850.jpg',
 '83855952.jpg',
 '80780727.jpg',
 '68546728.jpg',
 '1097445.jpg',
 '93710663.jpg',
 '82016486.jpg',
 '27506667.jpg',
 '80660077.jpg',
 '65884536.jpg',
 '63302988.jpg',
 '11542802.jpg',
 '68312500.jpg',
 '5620764.jpg',
 '95863104.jpg',
 '26418270.jpg',
 '1965723.jpg',
 '6044891.jpg',
 '46090301.jpg',
 '20634184.jpg',
 '66319241.jpg',
 '71857093.jpg',
 '26283134.jpg',
 '56800916.jpg',
 '97147723.jpg',
 '46182946.jpg',
 '43271445.jpg',
 '1976

In [0]:
#arr = np.array([np.array(Image.open(fname)) for fname in filelist], dtype=float)
#tmp = np.array(img).reshape(30,40,1)
#all_files = []
#basewidth = 40
#for fname in filelist:
#  imgg = Image.open(fname)
#  wpercent = (basewidth / float(imgg.size[0]))
#  hsize = int((float(imgg.size[1]) * float(wpercent)))
#  imgg = imgg.resize((basewidth, hsize), PIL.Image.ANTIALIAS)
#  tmp=np.array(imgg)
#  all_files.append(tmp)
  
#all_files = np.array(all_files, dtype=float)

In [0]:
all_files = []
for fname in filelist:
  imgg=Image.open(fname)
  tmp1 = imgg.resize((40,30))
  tmp = np.array(tmp1)
  all_files.append(tmp)

In [0]:
all_files = np.array(all_files,dtype=float)

In [0]:
all_files

array([[[[174., 171., 180.],
         [172., 169., 178.],
         [108., 105., 112.],
         ...,
         [193., 187., 189.],
         [ 92.,  80.,  80.],
         [136., 124., 126.]],

        [[164., 158., 168.],
         [181., 179., 193.],
         [124., 122., 127.],
         ...,
         [144., 138., 140.],
         [108., 108., 100.],
         [143., 134., 129.]],

        [[115., 109., 111.],
         [ 88.,  82.,  84.],
         [151., 148., 155.],
         ...,
         [128., 117., 115.],
         [ 82.,  78.,  69.],
         [ 74.,  63.,  57.]],

        ...,

        [[ 95.,  95.,  97.],
         [147., 129., 143.],
         [135., 134., 140.],
         ...,
         [103.,  91.,  95.],
         [156., 137., 141.],
         [118., 102., 103.]],

        [[ 88.,  88.,  90.],
         [132., 125., 133.],
         [138., 128., 136.],
         ...,
         [ 70.,  59.,  57.],
         [180., 159., 164.],
         [191., 175., 178.]],

        [[106., 103., 114.],
       

In [0]:
arr=all_files

In [0]:
np.shape(arr)

(792, 30, 40, 3)

In [0]:
X_train = arr
X_train = X_train.astype('float32')
X_train

array([[[[174., 171., 180.],
         [172., 169., 178.],
         [108., 105., 112.],
         ...,
         [193., 187., 189.],
         [ 92.,  80.,  80.],
         [136., 124., 126.]],

        [[164., 158., 168.],
         [181., 179., 193.],
         [124., 122., 127.],
         ...,
         [144., 138., 140.],
         [108., 108., 100.],
         [143., 134., 129.]],

        [[115., 109., 111.],
         [ 88.,  82.,  84.],
         [151., 148., 155.],
         ...,
         [128., 117., 115.],
         [ 82.,  78.,  69.],
         [ 74.,  63.,  57.]],

        ...,

        [[ 95.,  95.,  97.],
         [147., 129., 143.],
         [135., 134., 140.],
         ...,
         [103.,  91.,  95.],
         [156., 137., 141.],
         [118., 102., 103.]],

        [[ 88.,  88.,  90.],
         [132., 125., 133.],
         [138., 128., 136.],
         ...,
         [ 70.,  59.,  57.],
         [180., 159., 164.],
         [191., 175., 178.]],

        [[106., 103., 114.],
       

In [0]:
y_train = training_df['DGCI']
y_train = y_train.astype('float32')

In [0]:
test_df = pd.read_csv(io.StringIO(uploaded['sample.csv'].decode('utf-8')))

app_df = pd.DataFrame()
app_df['ResultColumn']=[str(xx)+'.jpg' for xx in test_df['Id']]


fillelist= app_df['ResultColumn'].tolist()

al_files = []
for fnname in fillelist:
  imgg=Image.open(fnname)
  tmp1 = imgg.resize((40,30))
  tmp = np.array(tmp1)
  al_files.append(tmp)


al_files = np.array(al_files,dtype=float)
X_test = al_files
X_test

array([[[[ 85.,  87.,  82.],
         [ 89.,  99.,  91.],
         [ 87.,  90.,  81.],
         ...,
         [ 63.,  83.,  72.],
         [ 72.,  96.,  82.],
         [ 53.,  81.,  69.]],

        [[133., 155., 143.],
         [ 70.,  86.,  73.],
         [ 83., 106.,  96.],
         ...,
         [ 69., 118.,  99.],
         [ 61.,  88.,  79.],
         [ 66.,  96.,  84.]],

        [[ 61.,  78.,  68.],
         [ 95., 136., 118.],
         [ 81., 104.,  94.],
         ...,
         [ 99., 117., 101.],
         [ 41.,  68.,  53.],
         [ 54.,  80.,  67.]],

        ...,

        [[102., 128., 117.],
         [ 81., 118., 110.],
         [116., 136., 125.],
         ...,
         [ 38.,  66.,  54.],
         [ 58.,  90.,  75.],
         [ 45.,  75.,  63.]],

        [[ 99., 126., 119.],
         [107., 127., 115.],
         [ 89., 115., 102.],
         ...,
         [ 63.,  96.,  85.],
         [ 71., 101.,  89.],
         [ 78., 112.,  98.]],

        [[103., 118., 115.],
       

In [0]:
X_test.shape

(528, 30, 40, 3)

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten

In [0]:
#model.add(tf.keras.layers.Dense(4, input_dim=4, kernel_initializer='normal', activation=tf.nn.relu))


In [0]:
#model.add(tf.keras.layers.Dense(2, kernel_initializer='normal',activation=tf.nn.relu))
from keras.layers.convolutional import Conv2D
from keras.layers.normalization import BatchNormalization
from keras.callbacks import LearningRateScheduler
from sklearn.cross_validation import train_test_split

In [0]:
model = Sequential()

model.add(Conv2D(32, kernel_size = 3, activation='relu', input_shape = (30,40,3)))
model.add(BatchNormalization())
model.add(Conv2D(32, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(32, kernel_size = 5, strides=2, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(64, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size = 5, strides=2, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1)) 

model.add(Conv2D(128, kernel_size = 4, activation='relu'))
model.add(BatchNormalization())
model.add(Flatten())
model.add(Dropout(0.1))
model.add(Dense(1,activation='linear'))

In [0]:
model.compile(optimizer="adam", loss='mse', metrics=['mae'])

In [0]:
model.fit(X_train, y_train, epochs = 1000, batch_size=64)

Epoch 1/1000
792/792 [==============================] - 15s 18ms/step - loss: 2.0463 - mean_absolute_error: 1.1105
Epoch 2/1000
792/792 [==============================] - 9s 12ms/step - loss: 2.8943 - mean_absolute_error: 1.0634
Epoch 3/1000
792/792 [==============================] - 9s 12ms/step - loss: 1.2434 - mean_absolute_error: 0.6766
Epoch 4/1000
792/792 [==============================] - 9s 12ms/step - loss: 0.5023 - mean_absolute_error: 0.5169
Epoch 5/1000
792/792 [==============================] - 9s 12ms/step - loss: 0.3890 - mean_absolute_error: 0.4081
Epoch 6/1000
792/792 [==============================] - 9s 12ms/step - loss: 0.2362 - mean_absolute_error: 0.3412
Epoch 7/1000
792/792 [==============================] - 9s 12ms/step - loss: 0.1983 - mean_absolute_error: 0.3225
Epoch 8/1000
792/792 [==============================] - 10s 12ms/step - loss: 0.1885 - mean_absolute_error: 0.3031
Epoch 9/1000
792/792 [==============================] - 9s 12ms/step - loss: 0.2137 - 

In [0]:
model.save('DGCII_th')


In [0]:
y_test=model.predict(X_test)

In [0]:
test_df['DGCI'] = y_test

In [0]:
test_df

Id      DGCI
0    79783930  0.482988
1    40239934  0.465688
2    50410534  0.512522
3    47165338  0.510816
4    16455157  0.512531
5    90938592  0.466567
6     1317745  0.520945
7    59791582  0.519664
8    14525631  0.505449
9    88602343  0.511632
10   23536231  0.524357
11   18553789  0.504189
12   81273029  0.493484
13   41102841  0.512071
14   67468796  0.507701
15   48298815  0.511114
16   93229470  0.485606
17   25785323  0.471326
18   30895645  0.502150
19   39503717  0.491754
20   91124259  0.495750
21   76528041  0.524361
22   73863630  0.494923
23   53397170  0.478221
24   64390024  0.504769
25    5495309  0.484867
26   96127913  0.502773
27   29592550  0.514018
28   53433017  0.533712
29   34588615  0.466753
..        ...       ...
498  63924227  0.522737
499  83306614  0.527510
500  52848860  0.522158
501  99303349  0.530496
502  21212656  0.491367
503  37807073  0.544094
504  55406826  0.472587
505    722409  0.529709
506  75855645  0.539088
507  90625918  0.494158
508  45254131  0.521243
509  41969652  0.523114
510  57602072  0.530203
511   4960703  0.506706
512  68239016  0.410598
513   1429593  0.528707
514   3771586  0.513494
515  16729575  0.525077
516  79745295  0.486160
517  20270223  0.491563
518   1698550  0.505666
519  16034595  0.538779
520  25987554  0.523525
521  74134655  0.535789
522   5508544  0.523336
523  64510039  0.504814
524  73548399  0.526616
525   7058044  0.508970
526  43963238  0.524889
527  94012606  0.504743

[528 rows x 2 columns]

In [0]:
test_df.to_csv("submit_dgci_perf.csv",index=False)

In [0]:
files.download("submit_dgci_perf.csv")