**Script for Challenge 4**

**Authors : Aditya Lahiri, Venkata Pydimarri, Vedant Mehta **


In [0]:
import pandas as pd
from google.colab import files 
import numpy as np

**PART 1: Wine Quality Linear Regression using white wine dataset**

In [85]:
uploaded_train_white = files.upload()


Saving winequality-white-training.csv to winequality-white-training (3).csv


In [86]:
uploaded_test_white = files.upload()


Saving winequality-white-testing.csv to winequality-white-testing (2).csv


In [87]:
for fn1 in uploaded_train_white.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn1, length=len(uploaded_train_white[fn1])))
  
for fn2 in uploaded_test_white.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn2, length=len(uploaded_test_white[fn2])))
  


User uploaded file "winequality-white-training.csv" with length 232528 bytes
User uploaded file "winequality-white-testing.csv" with length 57012 bytes


In [88]:
import io 
population_training_white_df = pd.read_csv(io.StringIO(uploaded_train_white['winequality-white-training.csv'].decode('cp1252')))
population_training_white_df.head(2)



Id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0   0            8.7              0.23         0.32            13.4   
1   1            5.0              0.27         0.40             1.2   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.044                 35.0                 169.0  0.99975  3.12   
1      0.076                 42.0                 124.0  0.99204  3.32   

   sulphates  alcohol  quality  
0       0.47      8.8        7  
1       0.47     10.1        6

In [0]:
X_train_white = population_training_white_df.iloc[:,1:12].values
y_train_white = population_training_white_df.iloc[:,12].values


In [90]:
population_testing_white_df= pd.read_csv(io.StringIO(uploaded_test_white['winequality-white-testing.csv'].decode('cp1252')))
population_testing_white_df.head(1)

Id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0   0            7.0              0.31         0.31             9.1   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.036                 45.0                 140.0  0.99216  2.98   

   sulphates  alcohol  
0       0.31     12.0

In [0]:
X_test_white = population_testing_white_df.iloc[:,1:12].values


**Apply linear regression **

In [92]:
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.linear_model import LinearRegression as LR

reg=LR(normalize=False)
reg.fit(X_train_white,y_train_white)
predict_train_white=reg.predict(X_train_white)
reg.score(X_train_white,y_train_white)

rmse = sqrt(mean_squared_error(y_train_white, predict_train_white))
rmse


0.7519290595321098

In [0]:
Y_test_white = reg.predict(X_test_white)
Coef_Mat_Sq=reg.coef_ 


In [94]:
Coef_Mat_Sq

array([ 6.19255832e-02, -1.83149523e+00,  3.15869785e-02,  7.87375964e-02,
       -4.89214094e-01,  3.58486991e-03, -3.27934802e-04, -1.44989006e+02,
        7.21238827e-01,  6.24079367e-01,  1.93168692e-01])

In [0]:
np.savetxt('winequality-white-solution.csv',Y_test_white,delimiter=",")
files.download('winequality-white-solution.csv')

In [0]:
np.savetxt('winequality-white-parameters.csv',Coef_Mat_Sq,delimiter=",")
files.download('winequality-white-parameters.csv')

In [0]:
Y_test_white

**Part 2: Apply Decision Tree on combined wine dataset**

In [98]:
uploaded_train_combined = files.upload()


Saving winequality-combined-training.csv to winequality-combined-training (5).csv


In [99]:
uploaded_test_combined = files.upload()


Saving winequality-combined-testing.csv to winequality-combined-testing (4).csv


In [100]:
for fn3 in uploaded_train_combined.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn3, length=len(uploaded_train_combined[fn3])))
  
for fn4 in uploaded_test_combined.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn4, length=len(uploaded_test_combined[fn4])))

User uploaded file "winequality-combined-training.csv" with length 302788 bytes
User uploaded file "winequality-combined-testing.csv" with length 79540 bytes


In [101]:
import io 
population_training_combined_df = pd.read_csv(io.StringIO(uploaded_train_combined['winequality-combined-training.csv'].decode('cp1252')))
population_testing_combined_df= pd.read_csv(io.StringIO(uploaded_test_combined['winequality-combined-testing.csv'].decode('cp1252')))
population_training_combined_df.head(2)


Id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0   0            8.7              0.23         0.32            13.4   
1   1            5.0              0.27         0.40             1.2   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.044                 35.0                 169.0  0.99975  3.12   
1      0.076                 42.0                 124.0  0.99204  3.32   

   sulphates  alcohol  type  
0       0.47      8.8     0  
1       0.47     10.1     0

In [0]:
X_train_combined = population_training_combined_df.iloc[:,1:12].values
y_train_combined = population_training_combined_df.iloc[:,12].values
X_test_combined = population_testing_combined_df.iloc[:,1:12].values


In [103]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
parameters = {'max_depth':range(1,40)}
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
clf = GridSearchCV(classifier, parameters)
clf.fit(X_train_combined, y_train_combined)
tree_model = clf.best_estimator_
tree_model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [104]:
y_pred_combined_train = tree_model.predict(X_train_combined)
y_pred_combined_test = tree_model.predict(X_test_combined)
print(y_pred_combined_test[:])

[0 0 0 ... 0 1 1]


In [105]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train_combined, y_pred_combined_train)
cm

array([[3898,    0],
       [  12, 1187]])

In [0]:
np.savetxt('winequality-combined-solution.csv',y_pred_combined_test,delimiter="")
files.download('winequality-combined-solution.csv')

**Part 3: Predict red wine using linear regression **



In [106]:
uploaded_train_red = files.upload()


Saving winequality-red-training.csv to winequality-red-training (1).csv


In [107]:
uploaded_test_red = files.upload()


Saving winequality-red-testing.csv to winequality-red-testing (1).csv


In [108]:
for fn5 in uploaded_train_red.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn5, length=len(uploaded_train_red[fn5])))
  
for fn6 in uploaded_test_red.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn6, length=len(uploaded_test_red[fn6])))

User uploaded file "winequality-red-training.csv" with length 69301 bytes
User uploaded file "winequality-red-testing.csv" with length 22158 bytes


In [109]:
import io 
population_training_red_df = pd.read_csv(io.StringIO(uploaded_train_red['winequality-red-training.csv'].decode('cp1252')))
population_testing_red_df= pd.read_csv(io.StringIO(uploaded_test_red['winequality-red-testing.csv'].decode('cp1252')))
population_training_red_df.head(2)

Id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0   0            9.1              0.60         0.00             1.9   
1   1            7.9              0.52         0.26             1.9   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.058                  5.0                  10.0   0.9977  3.18   
1      0.079                 42.0                 140.0   0.9964  3.23   

   sulphates  alcohol  quality  
0       0.63     10.4        6  
1       0.54      9.5        5

In [0]:
X_train_red = population_training_red_df.iloc[:,1:12].values
y_train_red = population_training_red_df.iloc[:,12].values
X_test_red = population_testing_red_df.iloc[:,1:12].values


In [111]:
from sklearn.linear_model import LinearRegression as LR

regressor_red=LR(normalize=False)
regressor_red.fit(X_train_red,y_train_red)
Y_test_red=regressor_red.predict(X_test_red)
regressor_red.score(X_train_red,y_train_red)


0.365508325866613

In [112]:
predict_train_red= regressor_red.predict(X_train_red)
rmse = sqrt(mean_squared_error(y_train_red,predict_train_red))
rmse

0.6416714607175982

In [0]:
np.savetxt('winequality-red-solution.csv',Y_test_red,delimiter=",")
files.download('winequality-red-solution.csv')

**Part 4: Use model reuse to predict on the testing set of red wine. **

In [114]:
reuse=reg
red_reuse_predict_train= reuse.predict(X_train_red)
red_reuse_predict_test=reuse.predict(X_test_red)
sqrt(mean_squared_error(y_train_red, (red_reuse_predict_train)))

0.9920773637017682

In [0]:
red_reuse_predict_test

In [0]:
np.savetxt('winequality-red-solution.csv',red_reuse_predict_test,delimiter=",")
files.download('winequality-red-solution.csv')