In [1]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Using TensorFlow backend.


x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 182s 3ms/step - loss: 0.2758 - acc: 0.9156 - val_loss: 0.0590 - val_acc: 0.9816
Epoch 2/12
60000/60000 [==============================] - 179s 3ms/step - loss: 0.0913 - acc: 0.9731 - val_loss: 0.0403 - val_acc: 0.9862
Epoch 3/12
60000/60000 [==============================] - 180s 3ms/step - loss: 0.0659 - acc: 0.9799 - val_loss: 0.0313 - val_acc: 0.9895
Epoch 4/12
60000/60000 [==============================] - 178s 3ms/step - loss: 0.0547 - acc: 0.9829 - val_loss: 0.0315 - val_acc: 0.9887
Epoch 5/12
60000/60000 [==============================] - 180s 3ms/step - loss: 0.0461 - acc: 0.9859 - val_loss: 0.0284 - val_acc: 0.9899
Epoch 6/12
60000/60000 [==============================] - 179s 3ms/step - loss: 0.0411 - acc: 0.9872 - val_loss: 0.0263 - val_acc: 0.9917
Epoch 7/12
60000/60000 [=========================

In [0]:
import numpy as np
import pandas as pd
import io

In [33]:
uploaded = files.upload()

Saving mnist_test.csv to mnist_test.csv


In [38]:
testing_df = pd.read_csv(io.StringIO(uploaded['mnist_test.csv'].decode('utf-8')))
testing_df.head()

Id  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0   1       0       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       0       0   
2   3       0       0       0       0       0       0       0       0       0   
3   4       0       0       0       0       0       0       0       0       0   
4   5       0       0       0       0       0       0       0       0       0   

     ...     pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0    ...            0         0         0         0         0         0   
1    ...            0         0         0         0         0         0   
2    ...            0         0         0         0         0         0   
3    ...            0         0         0         0         0         0   
4    ...            0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [62]:
testValues.shape

AttributeError: ignored

In [63]:
testValues = testing_df.drop(['Id'], axis=1).values
testValues = np.reshape(testValues, [len(testValues), 28, 28,1 ])
yPredictions = model.predict(np.array(testValues))
print(yPredictions)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [64]:
print(predictions[0])
print(max(predictions[0]))
predictedValues = [np.where(prediction == max(prediction))[0] for prediction in predictions]
print(predictedValues)

[2.1106333e-12 2.2785721e-12 8.0155924e-11 5.9828711e-11 2.9742593e-14
 1.4401993e-13 1.3504489e-17 1.0000000e+00 1.0259326e-12 4.1952983e-10]
1.0
[array([7]), array([2]), array([1]), array([0]), array([4]), array([1]), array([4]), array([9]), array([5]), array([9]), array([0]), array([6]), array([9]), array([0]), array([1]), array([5]), array([9]), array([7]), array([3]), array([4]), array([9]), array([6]), array([6]), array([5]), array([4]), array([0]), array([7]), array([4]), array([0]), array([1]), array([3]), array([1]), array([3]), array([4]), array([7]), array([2]), array([7]), array([1]), array([2]), array([1]), array([1]), array([7]), array([4]), array([2]), array([3]), array([5]), array([1]), array([2]), array([4]), array([4]), array([6]), array([3]), array([5]), array([5]), array([6]), array([0]), array([4]), array([1]), array([9]), array([5]), array([7]), array([8]), array([9]), array([3]), array([7]), array([4]), array([6]), array([4]), array([3]), array([0]), array([7]), 

In [0]:
import csv
from google.colab import files

In [0]:
with open("Predictions CNN MNist.csv", "w", newline='') as f:
    writer = csv.writer(f)
    writer.writerows(predictedValues)
files.download("Predictions CNN MNist.csv")