In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
wine_training_df1 = pd.read_csv('D:/Study/3rd Sem/ECEN 689/Challenge 4 - Wine Testing/Part 1/winequality-white-training.csv')
wine_testing_df1 = pd.read_csv('D:/Study/3rd Sem/ECEN 689/Challenge 4 - Wine Testing/Part 1/winequality-white-testing.csv')

In [3]:
wine_training_df = wine_training_df1.drop(labels='Id', axis=1) 

In [4]:
wine_testing_df = wine_testing_df1.drop(labels='Id', axis=1) 

In [35]:
x_train = wine_training_df.drop('quality', axis=1)

In [39]:
x_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               8.7             0.230         0.32           13.40      0.044   
1               5.0             0.270         0.40            1.20      0.076   
2               8.0             0.160         0.36            1.50      0.033   
3               5.8             0.280         0.35            2.30      0.053   
4               7.1             0.140         0.33            1.00      0.104   
5               7.5             0.300         0.21            6.55      0.026   
6               6.6             0.410         0.27           10.70      0.110   
7               6.2             0.300         0.32            1.20      0.052   
8               6.8             0.230         0.32            1.60      0.026   
9               6.8             0.220         0.31            1.40      0.053   
10              7.5             0.210         0.34            1.20      0.060   
11              6.0             0.170         0.30            7.30      0.039   
12              6.8             0.510         0.30            4.20      0.066   
13              5.8             0.190         0.49            4.90      0.040   
14              6.9             0.220         0.28            7.80      0.050   
15              7.4             0.410         0.34            4.70      0.042   
16              6.9             0.330         0.31            4.20      0.040   
17              8.1             0.200         0.49           11.80      0.048   
18              6.2             0.220         0.30           12.40      0.054   
19              7.6             0.250         0.34            1.30      0.056   
20              5.3             0.760         0.03            2.70      0.043   
21              6.0             0.260         0.29            3.10      0.041   
22              8.5             0.150         0.49            1.50      0.031   
23              5.5             0.160         0.31            1.20      0.026   
24              7.4             0.280         0.25           11.90      0.053   
25              6.6             0.520         0.44           12.20      0.048   
26              4.7             0.785         0.00            3.40      0.036   
27              5.7             0.210         0.32            1.60      0.030   
28              7.7             0.260         0.51            2.60      0.045   
29              5.9             0.230         0.24            3.80      0.038   
...             ...               ...          ...             ...        ...   
3868            7.0             0.290         0.37            4.90      0.034   
3869            6.3             0.150         0.34           11.40      0.050   
3870            5.5             0.485         0.00            1.50      0.065   
3871            7.8             0.300         0.29           16.85      0.054   
3872            7.1             0.365         0.14            1.20      0.055   
3873            7.5             0.180         0.72            9.60      0.039   
3874            6.4             0.310         0.31           12.90      0.045   
3875            6.9             0.330         0.28            1.30      0.051   
3876            7.4             0.160         0.30           13.70      0.056   
3877            6.4             0.230         0.33            1.15      0.044   
3878            7.4             0.350         0.20           13.90      0.054   
3879            6.3             0.210         0.28            1.50      0.051   
3880            7.2             0.230         0.39            1.50      0.053   
3881            7.0             0.240         0.51           11.00      0.029   
3882            7.3             0.190         0.27           13.90      0.057   
3883            8.1             0.200         0.28            0.90      0.023   
3884            6.0             0.250         0.40            5.70      0.052   
3885            7.6             0.520

In [6]:
x_test = wine_testing_df

In [7]:
from sklearn.linear_model import LinearRegression

In [9]:
lm = LinearRegression(normalize=True)
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [10]:
lm.fit(x_train,wine_training_df.quality)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [13]:
y_pred = lm.predict(x_test)

In [14]:
y_pred

array([ 6.37348187,  6.07681076,  5.86593525,  5.80255328,  5.6455453 ,
        6.46717636,  5.41160334,  5.49621366,  5.08901098,  5.77477465,
        5.79457995,  6.22677057,  5.59146125,  6.20371276,  5.24377582,
        5.63901853,  5.5024426 ,  6.6369013 ,  5.32793292,  5.99537033,
        6.66896326,  6.87821417,  6.47868595,  6.92247247,  5.31909298,
        4.97503913,  5.73846207,  5.42335738,  6.17600635,  5.56527928,
        6.66635111,  5.37891904,  5.87165377,  5.66235661,  6.75766804,
        5.53141212,  5.30691167,  5.53453926,  6.1951056 ,  5.47586005,
        5.90816163,  5.40536338,  6.00568625,  5.33136497,  5.68081122,
        6.45984001,  5.70944889,  5.75487264,  6.34592328,  5.51851696,
        5.35915886,  6.0678064 ,  5.19803342,  6.84205852,  3.76928166,
        6.19062397,  5.46548093,  6.03965258,  5.51985481,  5.59814109,
        5.99734478,  6.06961568,  6.28261104,  6.17410878,  6.06470448,
        5.60725079,  6.25240897,  6.37022732,  5.95165234,  6.97

In [19]:
m = len(wine_training_df.quality)

In [20]:
m

3898

In [105]:
x0 = np.ones(m)
X = np.array([x0, x_train['fixed acidity'], x_train['volatile acidity'], x_train['citric acid'], x_train['residual sugar'], x_train['chlorides'], x_train['free sulfur dioxide'], x_train['total sulfur dioxide'], x_train['density'], x_train['pH'], x_train['sulphates'], x_train['alcohol']]).T

In [106]:
X.shape

(3898, 12)

In [107]:
B = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
B.shape

(12,)

In [108]:
Y = np.array(wine_training_df.quality).T
alpha = 0.0001

In [109]:
Y

array([7, 6, 4, ..., 5, 6, 7], dtype=int64)

In [110]:
def cost_function(X, Y, B):
    m = len(Y)
    J = np.sum((X.dot(B) - Y) ** 2)/(2 * m)
    return J

In [111]:
inital_cost = cost_function(X, Y, B)
print(inital_cost)

17.6753463315


In [112]:
def gradient_descent(X, Y, B, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)
    
    for iteration in range(iterations):
        # Hypothesis Values
        h = X.dot(B)
        # Difference b/w Hypothesis and Actual Y
        loss = h - Y
        # Gradient Calculation
        gradient = X.T.dot(loss) / m
        # Changing Values of B using Gradient
        B = B - alpha * gradient
        # New Cost Value
        cost = cost_function(X, Y, B)
        cost_history[iteration] = cost
        
    return B, cost_history

In [119]:
# 100000 Iterations
newB = gradient_descent(X, Y, B, alpha, 100000)

In [122]:
newB

(array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
         nan]),
 [26.404652296113845,
  40.038196146241006,
  61.329055180862341,
  94.575802657049252,
  146.49010332680257,
  227.55135134608645,
  354.12176168152985,
  551.74881102752749,
  860.32157099179392,
  1342.1216536195311,
  2094.3937186706894,
  3268.9726904148984,
  5102.9291111258926,
  7966.4178860466172,
  12437.387892960391,
  19418.231348153182,
  30317.916662648513,
  47336.36527569194,
  73908.469198286897,
  115397.36682104428,
  180176.90317447286,
  281321.7512368937,
  439246.31715826789,
  685825.0485172061,
  1070825.7612853029,
  1671954.4455184622,
  2610538.9266935508,
  4076016.8688098383,
  6364170.6152864462,
  9936825.934196854,
  15515063.866387365,
  24224758.937303007,
  37823818.19933033,
  59056985.524890758,
  92209822.494140938,
  143973677.70315671,
  224796224.15739095,
  350990148.25504923,
  548025594.1504662,
  855670888.61745107,
  1336019116.2025774,
  2086020575.3